insert into Menu values(1, 'Carne Asada', 11.99);
insert into Menu values(2, 'De Camaron', 11.00);
insert into Menu values(3, 'Bisteak A La Mexicana', 9.99);
insert into Menu values(4, 'De Tilapia', 7.99);
insert into Menu values(5, '4 Tacos', 5.99);
insert into Menu values(6, 'Tostadas', 5.99);
insert into Menu values(7, 'Enchiladas', 5.99);
insert into Menu values(8, 'Kid Taco Platter', 3.99);
insert into Menu values(9, 'Kid Quesadilla', 3.99);
insert into Menu values(10, 'Kid Burrito', 3.99);
insert into Menu values(11, 'Nachos', 6.99);
insert into Menu values(12, 'Burrito', 6.50);
insert into Menu values(13, 'Quesadilla', 6.50);
insert into Menu values(14, 'Torta', 6.00);
insert into Menu values(15, 'Taco', 1.25);
insert into Menu values(16, 'Mini Sopapillas', 3.99);
insert into Menu values(17, 'Flan', 2.99);
insert into Menu values(18, 'Rice and Beans', 1.99);
insert into Menu values(19, 'French Fries', 1.99);
insert into Menu values(20, 'Avocado', 0.99);
insert into Menu values(21, 'Guacamole', 0.99);
insert into Menu values(22, 'Pico De Gallo', 0.50);
insert into Menu values(23, 'Sour Cream', 0.50);
insert into Menu values(24, 'Shrimp Cocktail', 11.00);
insert into Menu values(25, 'Green Wet Burrito', 7.50);
insert into Menu values(26, 'Carne Asada Fries', 6.50);
insert into Menu values(27, 'Guac. and Chips', 4.99);
insert into Menu values(28, 'Horchata', 1.79);
insert into Menu values(29, 'Jamaica', 1.79);
insert into Menu values(30, 'Fountain Drink', 1.79);
insert into Menu values(31, 'Jarritos', 1.79);
insert into Menu values(32, 'Fanta', 1.79);
insert into Menu values(33, 'Dasani', 1.79);
insert into Menu values(34, 'Corona', 3.25);
insert into Menu values(35, 'Modelo', 3.25);
insert into Menu values(36, 'Budlight', 2.50);
insert into Menu values(37, 'Budweiser', 2.50);
insert into Menu values(38, 'Tamale', 1.50);

