
package desktop;

import java.awt.Font;

import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.SimpleDateFormat;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

import java.awt.image.BufferedImage;

import java.io.File;

import java.io.IOException;

import java.text.DateFormat;
import java.text.ParseException;

import java.util.Date;

import javax.imageio.ImageIO;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas Nunez
 *
 */
public class Employee extends javax.swing.JFrame {

    /** Creates new form Employee */
    SimpleDateFormat fmt = new SimpleDateFormat("MMM/dd/yyyy");
    Font bfont = new Font("Verdana", Font.BOLD, 13);
    ImageIcon img = new ImageIcon("C:\\Users\\Nicolas Nunez\\Desktop\\tabit\\desktop\\src\\desktop\\logo.png");
    BufferedImage picture;
    File file;
    ImageIcon iicon;
    String filepath = "C:\\Users\\Nicolas Nunez\\Desktop\\tabit\\EmployeePictures\\";
    String picturepath;
    DataHandler databit;
    public Employee() throws SQLException {
        databit = new DataHandler();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        PicturePanel = new javax.swing.JPanel();
        LabelContainingPicture = new javax.swing.JLabel();
        PictureLabel = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoTextArea = new javax.swing.JTextArea();
        InformationLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ModifyTable = new javax.swing.JTable();
        ModifyLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        AddEmployee = new javax.swing.JButton();
        DeleteEmployee = new javax.swing.JButton();
        AddtoDB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setIconImage(img.getImage());

        PicturePanel.setBackground(new java.awt.Color(255, 255, 255));
        PicturePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        javax.swing.GroupLayout PicturePanelLayout = new javax.swing.GroupLayout(PicturePanel);
        PicturePanel.setLayout(PicturePanelLayout);
        PicturePanelLayout.setHorizontalGroup(
            PicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PicturePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LabelContainingPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        PicturePanelLayout.setVerticalGroup(
            PicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PicturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelContainingPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        PictureLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        PictureLabel.setForeground(new java.awt.Color(0, 0, 204));

        InfoPanel.setBackground(new java.awt.Color(51, 255, 255));
        InfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        InfoTextArea.setEditable(false);
        InfoTextArea.setColumns(20);
        InfoTextArea.setRows(5);
        InfoTextArea.setFont(bfont);
        InfoTextArea.setForeground(Color.blue);
        InfoTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(InfoTextArea);

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        InformationLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        InformationLabel.setForeground(new java.awt.Color(0, 0, 204));
        InformationLabel.setText("Employee Information");

        ModifyTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204), 3));
        ModifyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Last Name", "FirstName", "Date of Birth", "Position", "Salary", "PhoneNo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ModifyTable.setCellSelectionEnabled(true);
        ModifyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ModifyTable);
        ModifyTable.getColumnModel().getColumn(0).setResizable(false);
        ModifyTable.getColumnModel().getColumn(0).setPreferredWidth(4);
        ModifyTable.getColumnModel().getColumn(5).setResizable(false);
        DefaultTableModel dtm = (DefaultTableModel) ModifyTable.getModel();
        int rows = 0;
        System.out.println(rows);
        try {
            System.out.println(rows);
            rows = databit.getRows("Employee");
            System.out.println("It executed");
        }catch (SQLException e) {}
        System.out.println("# of rows " + rows);
        int rowsInTable = ModifyTable.getRowCount();
        while(rowsInTable < rows){
            dtm.addRow(new Object[]{null, null, null, null, null, null, null, null});
            rowsInTable++;
        }
        try{
            loadInventory(ModifyTable, rows);
        }catch(SQLException e) { }

        ModifyLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ModifyLabel.setForeground(new java.awt.Color(0, 0, 204));
        ModifyLabel.setText("Modify Employee Information");

        SaveButton.setBackground(new java.awt.Color(204, 255, 255));
        SaveButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        SaveButton.setText("Save Changes");

        Exit.setBackground(new java.awt.Color(204, 255, 255));
        Exit.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Exit.setText("Exit");

        AddEmployee.setBackground(new java.awt.Color(204, 255, 255));
        AddEmployee.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        AddEmployee.setText("New Employee");
        AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeActionPerformed(evt);
            }
        });

        DeleteEmployee.setBackground(new java.awt.Color(204, 255, 255));
        DeleteEmployee.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        DeleteEmployee.setText("Delete Employee");
        DeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmployeeActionPerformed(evt);
            }
        });

        AddtoDB.setBackground(new java.awt.Color(204, 255, 255));
        AddtoDB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        AddtoDB.setText("Add Employee");
        AddtoDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtoDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addComponent(ModifyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddtoDB, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PictureLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InformationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddEmployee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SaveButton))
                            .addComponent(AddtoDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeleteEmployee)
                                .addContainerGap())
                            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }//GEN-END:initComponents

    private void ModifyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyTableMouseClicked
        // TODO add your handling code here:
        Object o;
        int row = ModifyTable.rowAtPoint(evt.getPoint());
        int col = 0;
        o = ModifyTable.getModel().getValueAt(row, col);
        if( o == null) {
            System.out.println("Doesnt have a value yet");
        }
        else{
        int id = Integer.parseInt(o.toString());
        System.out.println(id);
            try {
                fillPictureLabel(id);
                fillInfoTextArea(id);
                loadPicturePanel(id);
            } catch (SQLException e) {} catch (IOException e) {
            }
        }
    }//GEN-LAST:event_ModifyTableMouseClicked

    private void AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) ModifyTable.getModel();
        dtm.addRow(new Object[] { null, null, null, null, null, null, null, null });
        int row = ModifyTable.getSelectedRow();
        System.out.println(row);
    }//GEN-LAST:event_AddEmployeeActionPerformed

    private void DeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmployeeActionPerformed
        // TODO add your handling code here:
        int row = ModifyTable.getSelectedRow();
        System.out.print("This is the row that is currently selected: " + row + "\n");
        Object o = ModifyTable.getModel().getValueAt(row, 0);
        if (o == null){
        ((DefaultTableModel)ModifyTable.getModel()).removeRow(row);
        }
        else{
            //TextDialog
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to delete this employee from the database?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                // Delete product from the database.
                int id = Integer.parseInt(o.toString());
                System.out.println(id);
                    try {
                        databit.deleteById("Employee", id);
                    } catch (SQLException e) {
                }
                ((DefaultTableModel)ModifyTable.getModel()).removeRow(row);        
            }
            else{
                System.out.println("Not confirmed");
            }
        }
    }//GEN-LAST:event_DeleteEmployeeActionPerformed

    private void AddtoDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtoDBActionPerformed
        // TODO add your handling code here:
        // this is where INSERTION WILL GET CALLED
        System.out.println("Adding to the Database");
        //Add records to database
        int id = -1;
        double Salary =-1;
        String FirstN="", LastN="", Position="", PhoneNo="", DOB="";
        boolean correct = true;
        int row = ModifyTable.getSelectedRow();
        for (int i = 0; i < ModifyTable.getColumnCount(); i++) {
            Object o;
            System.out.println("IM there");
            o = ModifyTable.getModel().getValueAt(row, 0);
            if (o == null) {
                JOptionPane.showMessageDialog(null, "Fill all fields");
                id = -1;
                correct = false;
                continue;
            } else
                id = Integer.parseInt(o.toString());
                o = ModifyTable.getModel().getValueAt(row, 1);
            if (o == null) {
                JOptionPane.showMessageDialog(null, "Fill all fields");
                LastN = "";
                correct = false;
                continue;
            } else {
                LastN = o.toString();
                LastN = LastN.toUpperCase();
            }
            o = ModifyTable.getModel().getValueAt(row, 2);
            if (o == null) {
                //                JOptionPane.showInputDialog(null, "WRONG");
                JOptionPane.showMessageDialog(null, "Fill all fields");
                FirstN = "";
                correct = false;
                continue;
            } else
                FirstN = o.toString();
                FirstN = FirstN.toUpperCase();
            
            o = ModifyTable.getModel().getValueAt(row, 3);
            if (o == null) {
                JOptionPane.showMessageDialog(null, "Fill all fields");
                DOB = "";
                correct = false;
                continue;
            } else if (!isDateValid( o.toString())){
                JOptionPane.showMessageDialog(null, "Date Format is: MON/DD/YYYY");
                DOB = "";
                correct = false;
                continue;
            }
                else{
                DOB = o.toString();
            }


            o = ModifyTable.getModel().getValueAt(row, 4);
            if (o == null) {
                JOptionPane.showMessageDialog(null, "Fill all fields");
                Position = "";
                correct = false;
                continue;
            } else
                Position = o.toString();
                Position = Position.toUpperCase();
            
            o = ModifyTable.getModel().getValueAt(row, 5);
            if (o == null) {
                JOptionPane.showMessageDialog(null, "Fill all fields");
                Salary = -1;
                correct = false;
                continue;
            } else
                //TotalCost = Float.parseFloat(o.toString());
                Salary = Double.parseDouble(o.toString());

            o = ModifyTable.getModel().getValueAt(row, 6);
            if (o == null) {
                JOptionPane.showMessageDialog(null, "Fill all fields");
                PhoneNo = "";
                correct = false;
                continue;
            } else
                PhoneNo = o.toString();
        }
            if (correct == true) {
                try {
                    databit.addNewEmployee(id, LastN, FirstN, DOB, Position, Salary, PhoneNo , "");
                } catch (SQLException e) {
                }
            }
        
    }//GEN-LAST:event_AddtoDBActionPerformed
    
    public static boolean isDateValid(String date) 
    {
            try {
                DateFormat df = new SimpleDateFormat(Inventory.FORMAT);
                df.setLenient(false);
               Date d= df.parse(date);
                System.out.println(d);
                return true;
            } catch (ParseException e) {
                return false;
            }
    }
    
    public void fillInfoTextArea(int id) throws SQLException {
        System.out.println("Executing!!!");
        this.InfoTextArea.setText(databit.getEmployeeInfo(id));
    }
    
    public void loadPicturePanel(int id) throws SQLException, IOException {
        if(databit.getEmployeePicture(id) == null){
            System.out.println("Picture path is not in DB");
            this.LabelContainingPicture.setIcon(null);
        }
        else{
            picturepath = this.filepath + databit.getEmployeePicture(id);
            System.out.println(picturepath);
            picture = ImageIO.read(new File(picturepath));
            iicon = new ImageIcon(picture);
            this.LabelContainingPicture.setIcon(iicon);
        }
        throw new IOException("There is something wrong");
    }
    
    public void fillPictureLabel(int id) throws SQLException{
        this.PictureLabel.setText(databit.getEmployeeName(id));
    }
    
    void loadInventory(JTable jt, int rows) throws SQLException {
        ResultSet inventory = databit.getAllEmployees();
        int i = 0;
            
        while (inventory.next()) {
            jt.getModel().setValueAt(inventory.getInt(1), i, 0);
            jt.getModel().setValueAt(inventory.getString(2), i, 1);
            jt.getModel().setValueAt(inventory.getString(3), i, 2);
            jt.getModel().setValueAt(fmt.format(inventory.getDate(4)), i, 3);
            jt.getModel().setValueAt(inventory.getString(5), i, 4);
            jt.getModel().setValueAt(inventory.getDouble(6), i, 5);
            jt.getModel().setValueAt(inventory.getString(7), i, 6);
            i++;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                new Employee().setVisible(true);
                }
                    catch(SQLException e){}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployee;
    private javax.swing.JButton AddtoDB;
    private javax.swing.JButton DeleteEmployee;
    private javax.swing.JButton Exit;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JTextArea InfoTextArea;
    private javax.swing.JLabel InformationLabel;
    private javax.swing.JLabel LabelContainingPicture;
    private javax.swing.JLabel ModifyLabel;
    private javax.swing.JTable ModifyTable;
    private javax.swing.JLabel PictureLabel;
    private javax.swing.JPanel PicturePanel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
